sudo: required
dist: trusty
language: rust
cache:
- apt
- cargo
rust:
- nightly
before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- cargo install cargo-travis || echo "cargo-travis already installed"
script:
- |
  cargo build &&
  cargo test
before_deploy:
- git config --local user.name "John Doe"
- git config --local user.email "john.doe@example.com"
- cargo build --release --target=x86_64-unknown-linux-gnu
- name="matrix-rocketchat-linux-x86_64"
- mkdir $name
- cp target/x86_64-unknown-linux-gnu/release/rust-release-test $name/
- cp LICENSE $name/
- tar czvf $name.tar.gz $name
deploy:
  provider: releases
  api_key:
    secure: "wNvR1WuMsqSwfOycN3qFqoG6EDrlt1VXSxIbsLQeLGid84lLQlzTjP6uEoJ0+KZmkoCzf5NisUsYISiXrmsH9hXqN7DZznJ34pGh3aQ57MdT1bJ49Qgm4f5eXjwdnRIsl5WnrOQYlXk2IZLJfC8D8sxtWciVig0akiqjqrutREGPd6mY3I0U9Cf1578amnP9H3NeWu6dU1lAK8wlXMZ8p5ZfZeMtKXGOMRZlnEWYOyYaakZ0bPOiehrnTfEfCoi5Ly1JbGNA0cX/xcGR0SdHWWh3NsT58AJ8Vz5adxIYuW4tesls3zKgIB68pdTXxeFEkR5yhyhEgGgQG5XjjrByWfPMlWVWQ2d32QBwsX8VS8mHkR9so9bHFz+PbQOQ7bBuumTtIpbA+lT+0koIBuDmrr5x0/ls6tQLiCOADACMno124xxQgOudCGTi3rnFHWimOif8RSk6wmLkg7DXHQG9kvgc3YTkkhyfSp3PZbpwixP6+Y//V2IOFKUS/HVFPTDCua2OgpnY2Un3ZCnlsAGhJKdOFzR3ZNkr4WhjTdloYW3ibPeSkaPCNIGVpsoWCQUfDideOKA5k5GWCSXfmG5yQk5YDMRNwUlsY6iaqbmd+p35Xyh2ZFsq1oY5O6S7cUBB6o0Tjr78uNmSMriHDsn9IHTv61cfZ8kzcCTmTFSMVw4="
  file_glob: true
  file: matrix-rocketchat-linux-x86_64.tar.gz
  on:
    repo: lerux/rust-release-test
    tags: true